<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Projet artistique Mylétoiles</title>
    <meta name="description" content="............"/>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <!-- Css -->
    <link rel="stylesheet" href="../public/css/style.css" type="text/css" media="screen" />
    <!-- Font Awesome 5 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" type="text/css" />
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Handlee&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Parisienne&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <!--<link rel="icon" type="image/png" href="img/favicon.png">
    <link rel="shortcut icon" href="img/favicon.ico">-->
    <!-- AJAX -->
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> -->
</head>



<body>

    <header class="header">
            
            <?php if (isset($_SESSION['admin'])):?>
            
            <nav id="mySidenav"class="navbar">
                <a id="closeBtn" href="#" class="close">×</a>
                <ul>
                    <li><a class="nav" href="index.php?page=home">Accueil</a></li>
                    <li><a class="nav" href="index.php?page=presentation">Présentation</a></li>
                    <li><a class="nav" href="index.php?page=paint_art">Artiste Peintre</a></li>
                    <li><a class="nav" href="index.php?page=gold_book">Livre d'Or</a></li>
                <div class="logo">
                    <li><a title="register" class="navinscription" href="index.php?page=register">
                        <i class="fa-solid fa-heart"></i>
                        </a>
                    </li>
                    <li><a title="login" class="naviconeCo" href="index.php?page=login">
                        <i class="fa-solid fa-user-check"></i>
                        </a>
                    </li>
                    <li><a title="logout" class="naviconeDeco" href="index.php?page=logout">
                        <i class="fa-solid fa-right-from-bracket"></i>
                        </a>
                    </li>
                </div>
                </ul>
            </nav>

        <a href="#" id="openBtn">
          <span class="burger-icon">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </a>
        
        <?php else: ?>
        <?php endif;?>
    </header>