<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Projet artistique Mylétoiles</title>
    <meta name="description" content="Projet développeur web"/>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <!-- Css -->
    <link rel="stylesheet" href="../public/css/style.css" type="text/css" media="screen" />
    <!--<link rel="stylesheet" href="../public/css/backOffice.css" type="text/css" media="screen" />-->
    <!-- Font Awesome 5 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" type="text/css" />
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Handlee&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Parisienne&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
</head>



<body>

    <header class="header">
            
            
    </header>