<div class="backoffice">

    <h2>Voici la liste des messages reçus!</h2>

<table class="backofficeLivredor">
    
    <?php foreach ($livredor as $message):?>

        <tr>
            <th>Utilisateur</th>
            <th>Message</th>
            <th>Date d'envoi</th>
        </tr>
        <tr>
            <td><?=htmlspecialchars($message["users_id"])?></td>
            <td><?=htmlspecialchars($message["message"])?></td>
            <td><?=htmlspecialchars($message["date_message"])?></td>
        </tr>
    
    <?php endforeach;?>
    
</table>
</div>