<form class="box" action="index.php?page=submitFormLogin" method="post" name="login">
    <h2 class="box-title">Connection</h2>
    
        <label for="email"></label>
                <input type="email" class="box-input" name="email" placeholder="Email" value="emilie.bld22@gmail.com"required>
    
        <div class="inputEye">
        <label for="password"></label>
            <input id="password" type="password" class="box-input" name="password" placeholder="Mot de passe" value="Mylena1408"required>
                <div id="eye">
                    <i class="fa-solid fa-eye-slash" id="logoEye"></i>
                </div>
        </div>

            <input type="submit" value="Valider" name="submit" class="box-button">
    
</form>