<div class="backoffice">

    <h2>Voici la liste des oeuvres exposées sur le site!</h2>

<table class="backofficePaint">
    
    <?php foreach ($oeuvre as $paint):?>

        <tr>
            <th>Id</th>
            <th>Titre</th>
            <th>Image</th>
            <th>Description</th>
            <th>Date</th>
        </tr>
        <tr>
            <td><?=htmlspecialchars($paint["id"])?></td>
            <td><?=htmlspecialchars($paint["title"])?></td>
            <td><?=htmlspecialchars($paint["name_image"])?></td>
            <td><?=htmlspecialchars($paint["description"])?></td>
            <td><?=htmlspecialchars($paint["date_paint"])?></td>
        </tr>
    
<?php endforeach;?>

</table>
</div>