<div class="backoffice">

    <h2>Voici la liste des utilisateurs ayant un compte sur le site!</h2>
    
<table class="backofficeUsers">
    
    <?php foreach ($users as $user):?>
    
    <tr>
        <th>Nom</th>
        <th>Email</th>
        <th>Type/role</th>
        <th>Date enregistrement</th>
    </tr>
    <tr>
        <td><?=htmlspecialchars($user["username"])?></td>
        <td><?=htmlspecialchars($user["email"])?></td>
        <td><?=htmlspecialchars($user["role_id"])?></td>
        <td><?=htmlspecialchars($user["register_date"])?></td>
    </tr>
    
<?php endforeach;?>

</table>
</div>


