<footer>
        <section class="me-contacter">
            <div class="contact">
                <address>
                    <h3>Contactez moi :</h3>
                    <i class="fas fa-store"></i> </a>Mylétoiles Store<br>
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2710.5396409377863!2d-1.646607984890835!3d47.20602242355743!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x480593549156659d%3A0xb45700c7c3ae5cb!2s10%20Rue%20des%20Marais%2C%2044800%20Saint-Herblain!5e0!3m2!1sfr!2sfr!4v1657100197619!5m2!1sfr!2sfr" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></br>
					<i class="fas fa-envelope"></i> <a href="mailto:myletoiles@gmail.com">myletoiles@gmail.com</a><br>
					<i class="fas fa-mobile"></i> <a href="tel:+33650901202">06-50-90-12-02</a>
				</address>
            </div>

            <div class="reseaux-sociaux">
                <h3>Suivez-moi :</h3>
                <div class="box-reseaux">
                    <div class="rs-f">
                        <a href="https://www.facebook.com/emy.b.4422">
                            <i class="fa-brands fa-facebook-f"></i>
                        </a>
                    </div>
                    <div class="rs-i">
                        <a href="https://www.instagram.com/emymyle/?hl=fr">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                    </div>
                </div>
            </div>
        </section>
        
</footer>

    <script src="./JS/script.js"></script>
    <script src="./JS/passwordEye.js"></script>
    <script src="./JS/searchArticle.js"></script>
</body>

</html>
