<footer>
        <section class="me-contacter">
            <div class="contact">
                <address>
                    <h3>Contactez moi :</h3>
					<i class="fas fa-store"></i>Mylétoiles-10 Rue des Marais 44800 St-Herblain<br>
					<i class="fas fa-envelope"></i> <a href="mailto:myletoiles@gmail.com">myletoiles@gmail.com</a><br>
					<i class="fas fa-mobile"></i> <a href="tel:+33650901202">06-50-90-12-02</a>
				</address>
            </div>

            <div class="reseaux-sociaux">
                <h3>Suivez-moi :</h3>
                <div class="box-reseaux">
                    <div class="rs-f">
                        <i class="fa-brands fa-facebook-f"></i>
                    </div>
                    <div class="rs-i">
                        <i class="fa-brands fa-instagram"></i>
                    </div>
                </div>
            </div>
        </section>
        
</footer>

    <script src="./JS/script.js"></script>
</body>

</html>
