<main>
    <div class="temoignage-all">
        <p>Parce qu'un retour de votre part fait toujours plaisir,</br>je vous invite à poster ici votre âme d'artiste...</p>
    
        <div class="temoignage">
            <!--boucle foreach for looping messages and display them-->
            <?php foreach($livredor as $message):?>
            
            <pre class="temoignage1">
                <p>-<strong><?=htmlspecialchars($message['username'])?></strong>-</p>
                <p>"<?=htmlspecialchars($message['message'])?>"</p>
                <p><?=htmlspecialchars($message['date_message'])?></p>
            </pre>
        <?php endforeach;?>
        </div>
    </div>
            
    <?php if(isset($_SESSION['logged']) && $_SESSION['logged'] == true): ?>
    
        <div class="form-gold-book">
            
            <form action="index.php?page=submitForm" method="POST">
                <fieldset>
                    <legend>Login</legend>
                    <?php
                        //If error table exist an sis not empty -> looping to errors to display one by one
                        if(isset($errors) && count($errors)>0){
                            foreach ($errors as $error){
                                echo $error."</br>";
                            }
                        }
                    ?>
                    <div class="textarea">
                        <p>J'écris mon message ...</p>
                        <textarea name="msg"></textarea>
                    </div>
                    <div class="btn">
                        <button type="submit">Envoyer</button>
                    </div>
                </fieldset>
            </form>
            
            <?php else: ?>
        <?php endif; ?>
        
    </div>
</main>