<form class="box" action="" method="post" name="login">
    <h1 class="box-title">Login</h1>
    
    <input type="text" class="box-input" name="email" placeholder="Email" required />
    <input type="password" class="box-input" name="password" placeholder="Password">
    <input type="submit" value="Valid" name="submit" class="box-button">
    
    <p class="box-register">Vous êtes nouveau ici? 
        <a href="index.php?page=register">S'inscrire</a>
    </p>
</form>
