


<body>
    
    <main>
        <div class="presentation-galerie">
            <p>Je m'appelle <strong> Myléna </strong>j'ai 7 ans et je suis en CE1.</p> 
            <p>Biensur ce n'est pas moi qui vous écrit mais ma maman, Emilie, 
            qui tient ce site afin de vous montrer les quelques réalisation que j'ai fait et que je vais faire 
            par la suite.</p>
            <p>Nous en avons discuté ensemble et avons pensé qu'il serait sympa de vous partager ce 
            qui me passionne et pourquoi pas de donner envie à d'autre enfant comme moi de s'essayer à l'art 
            quelqu'il soit, pour moi c'est la pienture.</p>
            <p>J'ai toujours aimé me renfermer dans la bulle le temps d'un instant
            pour poser sur la toile, ou même dans d'autre style de création, ce qui se renfermait dans mes pensées.</p>
        </div>
        <div class="galerie-grid">
            <figure class="box img1">
                <img class="image" src="public/pictures/arbreDeVie.jpg" alt="arbre de vie noir et or"/>
            </figure>

            <figure class="box img2">
                <img class="image" src="public/pictures/vert.jpg" alt="risières noires remplies d'une palette de verts"/>
            </figure>

            <figure class="box img3">
                <img class="image" src="public/pictures/ciel.jpg" alt="un air d'été avec ciel bleu et panier en osier"/>
            </figure>

            <figure class="box img4">
                <img class="image" src="public/pictures/colors.jpg" alt="feux d'artifice de couleurs"/>
            </figure>
            
            <figure class="box img5">
                <img class="image" src="public/pictures/orange.jpg" alt="abstrait orangé"/>
            </figure>
            
            <figure class="box img6">
                <img class="image" src="public/pictures/foret.jpg" alt="paysage d'automne sur une palette de violet"/>
            </figure>
        </div>
        
        <div class="blockquote">
        <blockquote lang="en">
            <p>"Grâce à l’art, au lieu de voir un seul monde, le nôtre, 
            nous le voyons se multiplier, et autant qu’il y ait d’artistes originaux, 
            autant nous avons de mondes à notre disposition."</p>
            <cite>- Marcel Proust -</cite>
        </blockquote>
        </div>
        <div class="source">
            <p>
                Sources:
                <a href="https://https://fr.wikisource.org/wiki/Page:Proust_-_Le_Temps_retrouv%C3%A9,_tome_2.djvu/53">Wikipedia</a>
            </p>
            <p class="icones">❦❦❦</p>
        </div>
    </main>
    
    
    
    
    