

<form class="box" action="" method="post">
	<h2 class="box-title">Register Form</h2>
	<input type="text" class="box-input" name="username" placeholder="Username" required />
    <input type="email" class="box-input" name="email" placeholder="Email" required />
	<div class="input-group">
			<select class="box-input" name="type" id="type" >
				<option value="" disabled selected>Type</option>
				<option value="1">Admin</option>
				<option value="2">User</option>
			</select>
	</div>
    <input type="password" class="box-input" name="password" placeholder="Password" required />
    <input type="submit" name="submit" value="valid" class="box-button" />
    
    <p class="box-register">Déjà inscrit? 
  <a href="index.php?page=login">Connectez-vous ici</a></p>
</form>


