<?php $i=1; ?>
    	<?php foreach($oeuvres as $oeuvre):?>
    	
    	
	    	<article>
	    		<a href="public/pictures/<?=htmlspecialchars($oeuvre['name_image'])?>" target="_blank">
					<img class="picture_oeuvre img-<?php if($i==1){echo 'left';} else{echo 'right';}?>" 
						src="public/pictures/<?=htmlspecialchars($oeuvre['name_image'])?>" alt="<?=htmlspecialchars($oeuvre['name_image'])?>">
				</a>
				<div class="oeuvre">
					<h2><?=htmlspecialchars($oeuvre['title'])?></h2>
					<p><?=htmlspecialchars($oeuvre['description'])?></p>
					<p class="outils"><strong>Outils utilisés</strong> : <?=htmlspecialchars($oeuvre['outil'])?></p>
				</div>
				<div class="clear"></div>
			</article>
		<?php $i++; ?>
		<?php if ($i==3){
			$i=1;
		}?>
    	<?php endforeach;?>

        <p>Nous avons trouvé <?= $numberOfArticles ?> article(s) correspondant à votre recherche</p>
        
        